### ISSUE TITLE
Build failure on Kubuntu 20.04

### ISSUE THREAD

**Issue by Kirtai** [dseagrav/ld#36]
I get the following error when trying to build on Kubuntu 20.04

```
gcc -std=gnu99 -Wall -Wextra -ggdb -g -O2 -DXBEEP -D_REENTRANT -I/usr/include/SDL2 -DSDL2 -Wno-packed-bitfield-compat -Og -DSYSCONFDIR=/usr/local/etc -lm  -o lam 3com.o lambda_cpu.o mem.o sdu.o smd.o tapemaster.o kernel.o nubus.o sdu_hw.o syms.o vcmem.o  -lSDL2 -lyaml
/usr/bin/ld: kernel.o: undefined reference to symbol 'sin@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by mnp** [comment]
Yeah I see that too on 20.04.  Try this workaround. Copy that "gcc..." link line, then `cd src` and try the link by hand but add an extra `-lm` onto the end. It seems order matters.

**Comment by Kirtai** [comment]
Yes, that worked, thank you. Very strange.

Some experimentation shows that the -lm has to be after the file that uses the symbol, kernel.o in this case. I wonder if it's a gcc bug of some sort, the order shouldn't matter like that.
